# Generated by Django 4.2 on 2023-04-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
