# Generated by Django 4.2 on 2023-04-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Approved ', 'Approved'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=12),
        ),
    ]
